# Třída Bird: Vykresluje ptáka
<Bird>
    size_hint: None, None
    # Rozměry na pevno (které se rovnají rozměrům textur)
    size: 68, 48
    # Středy v osách x, y
    center_x: 250
    center_y: 200

# Rotace (jenom obrázek)


    canvas.before:
        PushMatrix
        Rotate:
            angle: self.angle
            origin: self.center
    canvas.after:
        PopMatrix
        Color:
            rgba: 1, 1, 1, 1

